### ISSUE TITLE
Optimize Load Time

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-frontend#385] opened 2019-04-05 08:30 UTC
Yoroi is extremely slow to load. 

Running performance test on my MacBook Pro 2017, and first meaningful paint happens after 4 seconds. This is especially notable as the app is not loaded from the server, but is served from the local machine:

![image](https://user-images.githubusercontent.com/5859177/55614588-8a27b300-57b7-11e9-9a80-76c77bef7da1.png)

On my slower Dell, the FMP happens after ~7s. I wonder, what is the median load time for our users?

This is obviously the result of [huge bundles](#384) problem, but I think it's worth flagging this issue separately to bring attention to load time metrics.

I suggest adding Lighthouse check to CI and make sure that the FMP is under 500ms (or at least 1s to start with). 

@rcmorano, can you check how difficult it would be to do this, and if we can do it for an extension? Check out Preventing Regressions section here: https://developers.google.com/web/fundamentals/performance/user-centric-performance-metrics

**Comment by SebastienGllmt** [comment] 2019-04-05 08:36
This is a duplicate of #362 and already fixed

**Closed by SebastienGllmt** 2019-04-05 08:36 UTC
