### ISSUE TITLE
Releasing the left mouse button outside the input window when restoring a wallet closes the input window

### ISSUE THREAD

**Issue by Leo-Emurgo** [Emurgo/yoroi-frontend#389] opened 2019-04-08 05:41 UTC
Users will often switch tabs and switch focus back and forth when looking up their recovery phrase and/or password, and this easily leads to accidental clicks outside of the white area which results in all of the text entered so far being lost. 

Worse, simply sending a MOUSE_UP in the gray area also has the same effect. In Windows, MOUSE_UP almost never triggers an action except during Drag & Drop so this leads to accidentally closing the window along with confusion as to why the window is closing. 

For example, if you highlight text in any text box here and then release the button while the cursor is outside the white window, you lose everything. 

![Screenshot_2](https://user-images.githubusercontent.com/44602017/55700878-fef32b00-5a0b-11e9-9131-82bf856c1758.png)

**Comment by sarveshwar-singh** [comment] 2019-04-08 05:48
Similar to: https://github.com/Emurgo/yoroi-frontend/issues/46

**Comment by SebastienGllmt** [comment] 2019-04-08 06:31
I'll close as this is a duplicate as Shin mentioned.

**Comment by Leo-Emurgo** [comment] 2019-04-19 05:33
It's not exactly the same as that one. His issue does not mention "MOUSE UP" closing the window, which is the much larger problem. 

It also is still not fixed.

**Comment by nicarq** [comment] 2019-04-22 19:53
@PavelHaliakevich could you confirm 🙏

**Comment by SebastienGllmt** [comment] 2019-04-22 20:42
@nicarq this is fixed with the redesign PR for all dialog boxes.
@PavelHaliakevich you're welcome to test this on any build containing the redesign to see if it works as intended

**Closed by SebastienGllmt** 2019-04-22 20:42 UTC
Labels: Good first issue

**Comment by nicarq** [comment] 2019-04-22 20:44
@SebastienGllmt got it 👍

**Comment by PavelHaliakevich** [comment] 2019-04-24 10:24
> @nicarq this is fixed with the redesign PR for all dialog boxes.
> @PavelHaliakevich you're welcome to test this on any build containing the redesign to see if it works as intended

@SebastienGllmt @nicarq @Leo-Emurgo
Yeah, looks like it fixed. In the new design overlays and pop-ups can be closed only by clicking on the X button or by pressing the Esc. ( I'm not saying that I checked 100% of overlays, but will do eventually :) I will send a world if I find any issues with this.
