### ISSUE TITLE
Big bundles 

### ISSUE THREAD

**Issue by ebeloded** [Emurgo/yoroi-frontend#384] opened 2019-04-05 08:13 UTC
The combined weight of vendor and yoroi scripts are more than 21MB, which is enormous for a web application. 

![image](https://user-images.githubusercontent.com/5859177/55611671-62811c80-57b0-11e9-8201-966ee3d4973e.png)

This result of this is very long load time and huge memory use. Also, AdaLite is delivering almost the same functionality with only ~400KB, so the problem is not intrinsic to being a Cardano wallet.

@SebastienGllmt  mentioned that some meaningful reduction in size would come after transitioning to Webpack 4 (#362). Webpack 4 will definitely shake some trees and eliminate dead code. However, it seems that the big problem is with something else.

Running the package.json through bundlephobila[ showed](https://bundlephobia.com/scan-results?packages=aes-js@3.1.0,axios@0.18.0,bignumber.js@4.0.0,bip39@2.3.0,blakejs@1.1.0,bluebird@3.3.4,bs58@4.0.1,cardano-crypto.js@5.0.1,@cardano-foundation/ledgerjs-hw-app-cardano@1.0.6,cbor@4.1.4,classnames@2.1.3,crypto-random-string@1.0.0,es6-error@4.1.1,file-saver@1.3.8,lodash@4.17.11,lovefield@2.1.12,mobx@3.1.7,mobx-react@4.3.3,mobx-react-form@1.32.2,mobx-react-router@4.0.1,moment@2.21.0,pbkdf2@3.0.17,pdfjs-dist@2.0.943,qrcode.react@0.8.0,react@16.0.0,react-css-themr@2.1.2,react-dom@16.0.1,react-dropzone@4.2.3,react-intl@2.7.2,react-markdown@2.5.0,react-polymorph@0.8.0,react-router@4.1.2,react-router-dom@4.1.2,react-svg-inline@2.1.1,ringbufferjs@1.1.0,route-parser@0.0.5,semver@5.6.0,trezor-connect@7.0.2,validator@6.3.0,unorm@1.4.1) that, even though we have some heavy dependencies, such as pdfjs, the combined weight of them all is under 3MB.

Opening the _yoroi.bundle.js_ will show that it contains a lot of stuff that shouldn't be there, such as the information about where on @nicarq machine the project is stored 😱

![image](https://user-images.githubusercontent.com/5859177/55612512-98270500-57b2-11e9-93d8-68535edfcc4a.png)

TODO:
- [ ] Figure out what bloats the bundles and **how did it happen**
- [ ] Extract translations from the bundle and load only the required locale
- [ ] Split the code. Load heavy non-essential dependencies (such as pdfjs, trezor, ledger, etc) only when required
- [ ] Integrate Webpack Bundle Analyzer to see what else bloats our bundles and remove what we can

Additionally, I suggest adding a size check in CI. This is to ensure that when the process of deployment is automated, we can reliably fail if the bundle size spikes unexpectedly. @rcmorano let me know what you would need for that.

Yoroi deals with sensitive information and I think that every kilobyte of the app should be accounted for, and every dependency reconsidered.

**Comment by SebastienGllmt** [comment] 2019-04-05 08:35
This is a duplicate of #362 and a duplicate of the plugin system task

**Comment by ebeloded** [comment] 2019-04-05 09:03
Hey @SebastienGllmt, can we close the issues when the problems are resolved in production?

Also, this, and the #385 issues contain suggestions which are worthy to at least discuss.

**Comment by rcmorano** [comment] 2019-04-05 09:18
Hey, I can add a size-check-script step in our CI to check for the whole bundle size and/or for individual files. Something like...:

```
MAX_BUNDLE_SIZE=10240 # kb
MAX_VENDOR_SIZE=1024 # kb
BUNDLE_SIZE=$(du -xs /src/build/ | awk '{print $1}')
VENDOR_SIZE=$(du /src/build/js/vendor.js | awk '{print $1}')
test ! $BUNDLE_SIZE -gt $MAX_BUNDLE_SIZE || echo "ERR" && exit 1
test ! $VENDOR_SIZE -gt $MAX_VENDOR_SIZE || echo "ERR" && exit 1
```

**Comment by SebastienGllmt** [comment] 2019-04-05 09:24
Not sure if a check for individual files will be so useful because Mozilla has a strict per-file file size limit which we will use Webpack to enforce.

I'm not sure if a whole-application limit would be useful since we would have to just bump it up whenever we run against it. I can imagine a warning if your PR causes a sharp increase in app size to be useful in preventing a disaster in the future but maybe not a priority right now.

**Comment by SebastienGllmt** [comment] 2019-04-05 09:32
I am closing this again.

```Figure out what bloats the bundles and how did it happen & Integrate Webpack Bundle Analyzer to see what else bloats our bundles and remove what we can```
This is covered by #362 which is tracked in Clubhouse so this is a duplicate issue

```Extract translations from the bundle and load only the required locale```
This would only save a few kilobytes so probably not worth the engineering time (at least until we add a lot more language)

```Split the code. Load heavy non-essential dependencies (such as pdfjs, trezor, ledger, etc) only when required```
Having a plugin system is a non-trivial task and should go through the triage process and roadmap planning and not a Github issue

**Closed by SebastienGllmt** 2019-04-05 09:32 UTC
