### ISSUE TITLE
Wallet will not Sync for Ergo

### ISSUE THREAD

**Issue by savvyrobert** [Emurgo/yoroi-frontend#2461] opened 2021-10-19 15:32 UTC
![image](https://user-images.githubusercontent.com/50861819/137943340-ff02dc8d-1bb9-45a3-9f79-eaa05aad8b58.png)
 
There seems to be a type or something to do with "P" that is messing up the request to the API.

Please Advise.

**Comment by zuzunker** [comment] 2021-10-19 21:17
Hi, @savvyrobert! Please double-check if the issue is still reproducing at the moment, there has been some investigation and fixing done in collaboration with the Ergo foundation, I think it is ought to be resolved some time ago now.

**Comment by savvyrobert** [comment] 2021-10-19 21:32
@vsubhuman unfortunately the same error is occurring. Was even able to preproduce on another computer that has never had yoroi before.  Here is another message if it helps explain (a rollback).
![image](https://user-images.githubusercontent.com/50861819/137993749-a9d8a332-8f6f-4ad4-8dd0-291ec700e918.png)

**Comment by arobsn** [comment] 2021-10-19 23:40
@savvyrobert are you a miner? We are investigating this issue and the mining dust may be causing this.

**Comment by savvyrobert** [comment] 2021-10-20 01:27
@anon-br yes, any advice on what I should do in the interim?

**Comment by killke** [comment] 2021-10-20 01:58
[2021-10-20T10:55:25+09:00] RemoteFetcher::getTransactionsHistoryForAddresses error: {
  "stack": "Error: Request failed with status code 400
    at t.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/46.bundle.js:2:31769)
    at t.exports (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/46.bundle.js:2:34171)
    at XMLHttpRequest.d.onreadystatechange (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/46.bundle.js:2:27989)",
  "message": "Request failed with status code 400",
  "config": {}
}
[2021-10-20T10:55:25+09:00] batchedFetcher::batchGetTransactionsHistoryForAddresses error: {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "P",
  "stack": "P: api.errors.getTxHistoryForAddressesApiError: undefined
    at Object.errorFactory (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:91160)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:89104
    at async i (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:90873)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:91450
    at async P (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:87489)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86160
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86197
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86082
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:10241",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
[2021-10-20T10:55:25+09:00] ErgoApi::refreshTransactions error: {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "P",
  "stack": "P: api.errors.getTxHistoryForAddressesApiError: undefined
    at Object.errorFactory (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:91160)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:89104
    at async i (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:90873)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:91450
    at async P (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:87489)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86160
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86197
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86082
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:10241",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}
[2021-10-20T10:55:25+09:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.getTxHistoryForAddressesApiError: undefined",
  "name": "P",
  "stack": "P: api.errors.getTxHistoryForAddressesApiError: undefined
    at Object.errorFactory (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:91160)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:89104
    at async i (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:90873)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:91450
    at async P (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:87489)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86160
    at async Promise.all (index 0)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86197
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:86082
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_206d589d.bundle.js:1:10241",
  "id": "api.errors.getTxHistoryForAddressesApiError",
  "defaultMessage": "!!!Error received from server while getting txs.",
  "values": {}
}

i have the same problem.. 
I am miner and this txt my log file copy

**Comment by zuzunker** [comment] 2021-10-20 12:42
@savvyrobert @killke , it will be really great if you could provide the HAR file with network logs so we could see which calls exactly cause the problem and be able to debug the issue between the Yoroi backend and the Ergo explorer providing the data.

Here is an instruction on how the file can be saved in Chrome: https://support.google.com/admanager/answer/10358597?hl=en

**NOTE:**
1. No secret private information is ever transferred over network in Yoroi, so network logs only contain your addresses and responses from server about the state of your addresses, e.g. txs and utxos.
2. In order for the HAR log to capture the error you need to:
    - Open Yoroi
    - Open browser devtools and open the Network tab in the tools
    - Wait for some time for the error to occur in the background - it might be visible in the network tab as red entries - or alterantively you can reload the Yoroi page and open the wallet again, while devtools are open, to force the resync.
    - Then click download in the devtools to export the HAR file
3. You can send the HAR logs directly to me via email `ruslan(at)emurgo.io` to not have it attached to a public issue here on GitHub

**Comment by savvyrobert** [comment] 2021-10-21 00:19
@vsubhuman I sent you an email. If worse come to worst, I can mine .5 egro to an address you provide if you'd like to be able to troubleshoot it that way.

**Comment by zuzunker** [comment] 2021-10-22 10:34
> I sent you an email. If worse come to worst, I can mine .5 egro to an address you provide if you'd like to be able to troubleshoot it that way.

Thank you, @savvyrobert , I have received the HAR logs and we are analysing them at the moment to find the exact problem cause. I think there should be no need to do any special mining for this case, but I will ping you here in case we will need any additional help from miners in identifying edge cases 🙌

**Comment by arobsn** [comment] 2021-10-27 23:22
Fix deployed at the back-end, can you guys please confirm if your wallets are syncing now?

**Comment by arobsn** [comment] 2021-11-03 14:14
Closing in assumption that the issue has resolved.

**Closed as completed by arobsn** 2021-11-03 14:14 UTC
Labels: ergo

**Comment by savvyrobert** [comment] 2021-11-03 17:31
Fixed. Thank you very much for your time and effort.
