### ISSUE TITLE
Inconsistent fees charged for transferring same amount of ADA within the same wallet yoroi

### ISSUE THREAD

**Issue by besiwims** [Emurgo/yoroi-frontend#2235] opened 2021-07-15 15:13 UTC
Good day

I have made 4 transactions send 10ADA to 4 different yoroi wallet addresses from a yoroi wallet address. One of these transaction charged fees almost 5x than the other 3 which had the same fees. Do not mind that the amount transferred is small. See the 4 transactions below:

1. fee is 0.16. 10ADA transferred.

https://cardanoscan.io/transaction/5181a607ed45f3c1f907e1d964d90111dd7127384f8bf27be1e5fd50fa4cbc0d

2. fee is 0.16. 10ADA transferred.

https://cardanoscan.io/transaction/3f6b6ddbd24339d8793958c6c189c1756a99390371ed2c8069268bfbff2d3a2e

3. fee is 0.83. 10ADA transferred.

https://cardanoscan.io/transaction/81a099ca8c2965e73846ac181a327daf2a64ea32e6b23d404ec04786f105af4f

4. fee is 0.16. 10ADA transferred.

https://cardanoscan.io/transaction/a95a4460d69e1a930b9313cde412d101c072e1ce2c04d3beeb7ac8cc138f1bcb

This is like having 4 passengers in a bus travelling the same distance from the same point A to the same destination but one of them unluckily is charged 5x bus fee!

If it was network congestion pushing fees high why was my last transaction that happened shortly got charged 0.16 fee?

Why was it 5x more, not 2x?

As I am writing this, I just made another same transaction of same amount 10ADA to another account just to be sure of this problem but the fee is 0.16.

https://cardanoscan.io/transaction/535722f8b82c4227ce1490f212de6c4d5cdee0b5dbc5d95ca9f4ab35ae17bb69

Some people have explained this with utxo fees links calculations but from a consumer and/or legal point of view this is not acceptable.

**Comment by zuzunker** [comment] 2021-07-16 10:53
Hello, @besiwims! Thank you for your detailed report, the provided details help very much and allowed us to identify the problem very quickly!

I am sorry for the situation, we can see now that this difference in fees has indeed been caused by the UTxO-selection rules. The rules always so far have been such that if the wallet finds a UTxO that covers the sending amount and the fees (in this case the UTxO was for `10.831727` ADA) it then check if after subtracting the sending amount and the required fee it is still possible to send the rest of the amount back as change (in this case the change would be approximately `0.663454` ADA). But because of the changes in the Cardano protocol itself - it is now impossible to have a UTxO and thus a change value to be less than 1 full ADA.

And the wallet did not use more inputs, as the general rule for the coin-selection always was to minimize the inputs as much as possible, which might have been fine while the price of a single coin was around `$0.10` , but now I will agree the priorities must be updated.

We will add a change to the next version that will ensure this will be mitigated **whenever possible** (important to remember that this is technically impossible to change in those cases when the entire balance of the wallet is less than 1 ada greater than the sending amount plus fees, so if the wallet would only have `10.8` ADA and you would try to send `10` ADA - it would be technically impossible to avoid spending this big fee) , but I can see that it is possible to change it for your case.

**Comment by besiwims** [comment] 2021-07-16 13:59
Great. That's what I love about Cardano.

**Comment by zuzunker** [comment] 2021-08-04 11:44
@besiwims , this is now resolved in the just release extension version 4.6

**Closed as completed by zuzunker** 2021-08-04 11:44 UTC
Labels: fix for next version, tx-builder, change-required (confirmed)
