### ISSUE TITLE
Cannot calculate fee when trying to send ADA

### ISSUE THREAD

**Issue by efegure** [Emurgo/yoroi-frontend#2414] opened 2021-09-25 19:13 UTC
![image](https://user-images.githubusercontent.com/15102957/134783589-90ea04b4-762d-4f0d-830c-4ca719136993.png)

Logs:

`[INFO] Yoroi v.4.7.300
[INFO] Commit: ef65039efb16a0eb881d3a9a160bf40f258cc0f6
[INFO] Network: mainnet
[INFO] User Agent: { ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36',
  browser: { name: 'Chrome', version: '94.0.4606.61', major: '94' },
  engine: { name: 'Blink', version: '94.0.4606.61' },
  os: { name: 'Windows', version: '10' },
  device: { vendor: undefined, model: undefined, type: undefined },
  cpu: { architecture: 'amd64' } }

[2021-09-25T22:08:07+03:00] batchedFetcher::batchGetTokenInfo error: {
  "stack": "TypeError: Cannot read properties of undefined (reading 'status')
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1765017
    at async Promise.all (index 48)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1765190
    at async Promise.all (index 1)
    at async chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1770274
    at async Ie (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/544.bundle.js:1:1302258)
    at async N (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/618.bundle.js:1:45470)
    at async s.<anonymous> (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_ef4bde61.bundle.js:1:259704)",
  "message": "Cannot read properties of undefined (reading 'status')"
}
[2021-09-25T22:08:22+03:00] AdaApi::createUnsignedTxForUtxos error: "Maximum output size of 5000 exceeded. Found: 5060"
[2021-09-25T22:08:27+03:00] AdaApi::createUnsignedTxForUtxos error: {
  "message": "api.errors.CannotSendBelowMinimumValueError: undefined",
  "name": "g",
  "stack": "g: api.errors.CannotSendBelowMinimumValueError: undefined
    at Y (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:109076)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:107392
    at Z (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:107536)
    at Te.createUnsignedTxForUtxos (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:10320)
    at Te.createUnsignedTx (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:11434)
    at async i._method (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_ef4bde61.bundle.js:1:138233)",
  "id": "api.errors.CannotSendBelowMinimumValueError",
  "defaultMessage": "!!!Cannot send amount below required minimum.",
  "values": {}
}
[2021-09-25T22:08:31+03:00] AdaApi::createUnsignedTxForUtxos error: "Maximum output size of 5000 exceeded. Found: 5060"
[2021-09-25T22:08:43+03:00] AdaApi::createUnsignedTxForUtxos error: "Maximum output size of 5000 exceeded. Found: 5060"
[2021-09-25T22:08:47+03:00] AdaApi::createUnsignedTxForUtxos error: {
  "message": "api.errors.CannotSendBelowMinimumValueError: undefined",
  "name": "g",
  "stack": "g: api.errors.CannotSendBelowMinimumValueError: undefined
    at Y (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:109076)
    at chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:107392
    at Z (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:107536)
    at Te.createUnsignedTxForUtxos (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:10320)
    at Te.createUnsignedTx (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_868f51f5.bundle.js:1:11434)
    at async i._method (chrome-extension://ffnbelfdoeiohenkjibnmadjiehjhajb/js/yoroi_ef4bde61.bundle.js:1:138233)",
  "id": "api.errors.CannotSendBelowMinimumValueError",
  "defaultMessage": "!!!Cannot send amount below required minimum.",
  "values": {}
}
[2021-09-25T22:08:49+03:00] AdaApi::createUnsignedTxForUtxos error: "Maximum output size of 5000 exceeded. Found: 5060"
[2021-09-25T22:08:54+03:00] AdaApi::createUnsignedTxForUtxos error: "Maximum output size of 5000 exceeded. Found: 5060"`

**Comment by zuzunker** [comment] 2021-09-25 21:47
Most probably should be fixed by this: https://github.com/Emurgo/cardano-serialization-lib/pull/206

The change is already merged there so need to publish it and release new version of Yoroi.

**Comment by zuzunker** [comment] 2021-09-25 23:28
Hi, @efegure! Thank you for the detailed report and the logs, this is extremely helpful! 🙌 

New extension version `4.7.310` is published now. Once you get your installed version updated, whenever possible, test it out again, please.

**Comment by zuzunker** [comment] 2021-09-29 15:19
Considered to be resolved unless @efegure can confirm if the issue is still reproducible

**Closed as completed** 2021-10-04 09:56 UTC
Labels: closing-candidate, tx-builder, in-progress
