### ISSUE TITLE
Cannot harvest from Sundae.fi

### ISSUE THREAD

**Issue by nullprobe** [Emurgo/yoroi-frontend#3318] opened 2023-10-19 07:52 UTC
I am not able to harvest rewards from the sundae.fi app. The Sundae team looked into it but eventually pointed me towards Yoroi, as they believe the issue lies there. 

Currently running this, but it has been and ongoing issue for months : 

Current version: [4.22.610]
Commit: [4c3ac323852744e5073b6f56b5a343c0192dd64a]

Once I sign the transaction using the Yoroi dApp connector nothing further happens, and this error is thrown in the console : 

![image](https://github.com/Emurgo/yoroi-frontend/assets/2757396/4ba2bf22-6554-482f-8920-d6449cf2ca25)

**Comment by Nebyt** [comment] 2023-10-19 08:32
Hi @nullprobe ! Thank you for your report! Could you please tell, do you have other cryptocurrencies wallets?

**Comment by nullprobe** [comment] 2023-10-19 08:37
Hi @Nebyt , Metamask is also there but it was also failing to work before Metamask was installed.

**Comment by Nebyt** [comment] 2023-10-19 10:02
@nullprobe Could you please try to switch off Metamask? I asking because, previously we had an error with Sundae, but we fixed it. Also the error is located in the file that is not belong to Yoroi.

**Comment by nullprobe** [comment] 2023-10-19 10:46
Disabled MM, same issue. Any debug logs I can provide you?

**Comment by nullprobe** [comment] 2023-10-19 10:52
Some additional verbose logs : 

VM6:49 page received from connector: {"type":"connector_rpc_response","protocol":"cardano","uid":232,"return":{"err":{"code":2,"info":{"error":{"response":"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (AlonzoInBabbageUtxoPredFailure (TooManyCollateralInputs 3 5)))])"}}}}} with source = [object Window] and origin = https://app.sundae.fi

**Comment by Nebyt** [comment] 2023-10-19 11:10
Thank you @nullprobe !

**Comment by Cognacy** [comment] 2023-10-24 01:26
> Some additional verbose logs :
> 
> VM6:49 page received from connector: {"type":"connector_rpc_response","protocol":"cardano","uid":232,"return":{"err":{"code":2,"info":{"error":{"response":"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (AlonzoInBabbageUtxoPredFailure (TooManyCollateralInputs 3 5)))])"}}}}} with source = [object Window] and origin = https://app.sundae.fi

Hi @nullprobe are you still having this error?

**Comment by nullprobe** [comment] 2023-10-25 08:16
> > Some additional verbose logs :
> > VM6:49 page received from connector: {"type":"connector_rpc_response","protocol":"cardano","uid":232,"return":{"err":{"code":2,"info":{"error":{"response":"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (AlonzoInBabbageUtxoPredFailure (TooManyCollateralInputs 3 5)))])"}}}}} with source = [object Window] and origin = https://app.sundae.fi
> 
> Hi @nullprobe are you still having this error?

Yes
Has a fix been pushed or what?

**Comment by Nebyt** [comment] 2023-10-25 12:37
@nullprobe User Cognacy is not from the Emurgo team. We are still investigating the error.

**Comment by nullprobe** [comment] 2023-11-06 13:20
Hi @Nebyt , any update on this?

**Comment by Nebyt** [comment] 2023-11-07 06:55
Hi @nullprobe , sorry for the long response, no updates from our side. We are quite occupied with tasks.

**Comment by nullprobe** [comment] 2023-11-29 12:49
Hi @Nebyt , checking in again. Do you have an ETA on a fix?
Meanwhile, my funds are still locked...

**Comment by Nebyt** [comment] 2023-12-05 11:13
Hi @nullprobe ! Sorry again for the long response. We have been working on the fix. Hopefully, it will be in the nearest release 5.0, which we are going to publish this week.

**Comment by Nebyt** [comment] 2023-12-08 13:47
@nullprobe The version 5.0.0 is released. Could you please check, does the issue still persist or not?

**Comment by nullprobe** [comment] 2023-12-08 13:54
Can confirm it works! Thanks. 
Do you need extra info before closure?

**Comment by Nebyt** [comment] 2023-12-08 16:52
If it works we can close it 😃 
Thank you for providing the issue with verbose console logs, it is really helpful! 🙌

**Comment by Nebyt** [comment] 2023-12-08 16:54
The issue is fixed in [release 5.0](https://github.com/Emurgo/yoroi-frontend/releases/tag/5.0.0)

**Closed as completed by Nebyt** 2023-12-08 16:54 UTC
