### ISSUE TITLE
extension completely broken for HW wallets (ledger) - indefinite syncing due to GenericApiError

### ISSUE THREAD

**Issue by benapetr** [Emurgo/yoroi-frontend#2448] opened 2021-10-07 09:48 UTC
Hello,

I had a working Yoroi in firefox that was connected to my ledger nano S, that suddenly stopped syncing. I tried deleting it and adding again, I tried using different browsers, and even completely different computers that never had Yoroi installed.

It just doesn't seem to work anymore, I just see spinning wheels.

These are logs:

```
[INFO] Yoroi v.4.7.400.0
[INFO] Commit: 64ae9837afe3347f8ae7d7af0b8ec98d03e2a1c2
[INFO] Network: mainnet
[INFO] User Agent: { ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:89.0) Gecko/20100101 Firefox/89.0',
  browser: { name: 'Firefox', version: '89.0', major: '89' },
  engine: { name: 'Gecko', version: '89.0' },
  os: { name: 'Mac OS', version: '10.14' },
  device: { vendor: undefined, model: undefined, type: undefined },
  cpu: { architecture: undefined } }
----
[2021-10-07T11:45:16+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)."
[2021-10-07T11:45:16+02:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "t@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/275.bundle.js:2:302834
c@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_ef4bde61.bundle.js:1:3707
l@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:134800
refreshTransactions@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:3111
",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
[2021-10-07T11:45:35+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)."
[2021-10-07T11:45:35+02:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "t@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/275.bundle.js:2:302834
c@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_ef4bde61.bundle.js:1:3707
l@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:134800
refreshTransactions@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:3111
",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
[2021-10-07T11:45:55+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)."
[2021-10-07T11:45:55+02:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "t@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/275.bundle.js:2:302834
c@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_ef4bde61.bundle.js:1:3707
l@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:134800
refreshTransactions@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:3111
",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
[2021-10-07T11:46:15+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)."
[2021-10-07T11:46:15+02:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "t@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/275.bundle.js:2:302834
c@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_ef4bde61.bundle.js:1:3707
l@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:134800
refreshTransactions@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:3111
",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
[2021-10-07T11:46:35+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)."
[2021-10-07T11:46:35+02:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "t@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/275.bundle.js:2:302834
c@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_ef4bde61.bundle.js:1:3707
l@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:134800
refreshTransactions@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:3111
",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}
[2021-10-07T11:46:55+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29)."
[2021-10-07T11:46:55+02:00] WalletStore::refreshWalletFromRemote {
  "message": "api.errors.GenericApiError: undefined",
  "name": "l",
  "stack": "t@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/275.bundle.js:2:302834
c@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_ef4bde61.bundle.js:1:3707
l@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:134800
refreshTransactions@moz-extension://34132d26-6ff7-084d-8d0a-0c80666d44c5/js/yoroi_868f51f5.bundle.js:1:3111
",
  "id": "api.errors.GenericApiError",
  "defaultMessage": "!!!An error occurred, please try again later.",
  "values": {}
}

```

**Comment by wirefreethought** [comment] 2021-10-19 20:59
I have the same issue on Mac OSX, regardless of the browser. See my post in the forums:

https://forum.cardano.org/t/yoroi-blank-page-after-alonzo-upgrade/78978

**Comment by benapetr** [comment] 2021-10-20 08:35
I am also using MacOS

**Comment by rooooooooob** [comment] 2021-11-03 17:45
I don't know what the root cause would be but in case this helps anyone working on it I just wanted to point this out that
>[2021-10-07T11:46:55+02:00] AdaApi::refreshTransactions error: "Deserialization failed in Ed25519KeyHash because: Invalid cbor: expected tuple 'hash length' of length 28 but got length Len(29).

This could be mixing up the keyhash portion of a enterprise or non-staking address (28 bytes) with the entire address (29 bytes - 1 byte for the address header)

I thought it could also be the cbor bytes are being treated as the keyhash itself, so you have the 1 extra byte for the cbor bytes tag, but afaik that can only encode the type+length in one single byte when the length is <24 and this would be 28.

**Comment by benapetr** [comment] 2021-12-17 10:49
@rooooooooob just want to point out that this wallet is also used with Daedalus where it works absolutely normally, it's not using any enterprise addresses, it's staked. This has to be a bug in Yoroi.

**Comment by zuzunker** [comment] 2021-12-17 11:19
There is a bug in Yoroi and it is being investigated at the moment. As soon as we have a fix for this a new release will be pushed.

**Comment by FredWahl** [comment] 2022-01-05 00:04
Ah, so that’s why yoroi didn’t work for me.

**Closed as completed** 2022-01-20 09:45 UTC
Labels: in-progress
