### ISSUE TITLE
Cannot connect ledger nano s plus to yoroi

### ISSUE THREAD

**Issue by daamiian** [Emurgo/yoroi-frontend#2971] opened 2022-08-19 13:30 UTC
Ledger turned on, unlocked, and connected to the cardano app (open). When I try to connect to Ledger nano s, on the "connect" section, it gives me the error:

> Unexpected error occurred. Please retry.

**Comment by Nebyt** [comment] 2022-08-19 14:06
Hi @daamiian. Thank you for your report.
Could you, please, provide to us more additional info?
What is your browser?
What is version of your browser?
What is the version of the Yoroi extension?
What is the version of the Ledger firmware?
What is the version of the Cardano app?

**Comment by daamiian** [comment] 2022-08-19 15:16
Firefox 103.0.2 (64-bit)
Extension is brand new, added today
firmware 1.0.3
I don't know the version of the cardano app, but it's up to date.

**Comment by zuzunker** [comment] 2022-08-19 15:20
> Firefox 103.0.2 (64-bit) Extension is brand new, added today firmware 1.0.3 I don't know the version of the cardano app, but it's up to date.

Thank you, @daamiian. The issue is identified now, happens with the latest version of Firefox, because some APIs have changed there. We are working on the fix at the moment, the new version `4.16.200` will be released for this today. Only latest Firefox is affected, so in case you need urgent access the workaround would be to use any chromium browser, for example.

**Closed as completed** 2022-08-24 19:41 UTC
Labels: in-testing
